import { NextRequest, NextResponse } from 'next/server';
import aws4 from 'aws4';
import { getProfileByUser } from '@/lib/profileService';

export async function POST(req: NextRequest) {
  try {
    const { userId } = await req.json();
    
    // Validate request
    if (!userId) {
      return NextResponse.json({ error: 'Missing userId' }, { status: 400 });
    }

    const endpoint = process.env.NEXT_PUBLIC_CHAT_API_URL;
    const credentials = {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
    };

    // If AWS isn't fully configured, return the polished mock payload
    if (!endpoint || !credentials.accessKeyId || !credentials.secretAccessKey) {
      await new Promise(r => setTimeout(r, 2000));
      const mockAiPlan = `Based on your recent daily logs and clinical data, here is your synthesized daily plan:
      
### ☀️ Morning Routine
- **Hydration Kickstart**: Drink 1 large glass (16oz) of water immediately upon waking to counteract overnight dehydration.
- **Heart-Healthy Breakfast**: Swap processed cereals for oatmeal with chia seeds. This specifically targets lowering your LDL cholesterol currently in the risk band.
- **Medication Compliance**: Take your BP medication with food at 8:30 AM.

### 🏃‍♂️ Midday Activity
- **Movement Snack**: Break up sedentary blocks. Based on your recorded 7,500 steps, let's push for a 15-minute brisk walk after lunch to reach 9,000 steps today.
- **Stress Management**: You recorded a stress level of 8/10 yesterday. Dedicate 5 minutes to box-breathing at 2 PM.

### 🌙 Evening Wind-down
- **Smoking Cessation**: You successfully reduced your intake to 4 cigarettes yesterday! If a craving hits post-dinner, try chewing cinnamon gum.
- **Sleep Hygiene**: Disconnect from screens by 10 PM. You've averaged only 6 hours of sleep this week, which significantly impacts blood pressure recovery.

*Generated by Prosper Bedrock AI Engine (Mock Fallback).*`;

      return NextResponse.json({ success: true, plan: mockAiPlan });
    }

    // Call Real Bedrock AI
    const url = new URL(endpoint);
    const host = url.hostname;
    const path = url.pathname;

    const userProfile = await getProfileByUser(userId);

    const systemPrompt = `You are a medical AI assistant. The user needs a highly personalized 3-part daily health plan. Output exactly 3 markdown headers (### ☀️ Morning Routine, ### 🏃‍♂️ Midday Activity, ### 🌙 Evening Wind-down) with bullet points beneath them containing actionable, specific medical/lifestyle advice based strictly on their profile data below. Do not include introductory conversational text.`;

    const enrichedBody = {
      inputText: systemPrompt,
      userId: userId,
      userContext: userProfile ? {
        age: userProfile.age,
        gender: userProfile.gender,
        activityLevel: userProfile.activityLevel,
        familyHistory: userProfile.familyHistory,
        medicalConditions: userProfile.medical?.conditions,
        medications: userProfile.medical?.medications,
        allergies: userProfile.medical?.allergies,
        diet: userProfile.diet,
        lifestyle: userProfile.lifestyle,
        smoker: userProfile.smoker,
        hypertension: userProfile.hypertension,
        diabetes: userProfile.diabetes
      } : {}
    };

    const opts: aws4.Request = {
      host,
      path,
      method: 'POST',
      body: JSON.stringify(enrichedBody),
      headers: {
        'Content-Type': 'application/json',
      },
      service: 'execute-api',
      region: process.env.AWS_REGION || 'ap-south-1',
    };

    // Sign the request mapped to API Gateway
    aws4.sign(opts, credentials);

    const response = await fetch(endpoint, {
      method: opts.method,
      headers: opts.headers as HeadersInit,
      body: opts.body as BodyInit,
    });

    const data = await response.json();

    if (!response.ok) {
      console.error('AWS API Error:', data);
      throw new Error('Bedrock backend rejected the prompt.');
    }

    const parsed = typeof data.body === 'string' ? JSON.parse(data.body) : data;
    const aiText = parsed.response || parsed.message || "Failed to generate.";

    return NextResponse.json({ success: true, plan: aiText });

  } catch (error: any) {
    console.error('API /health-plan/generate Error:', error);
    return NextResponse.json({ error: 'Failed to generate plan securely.' }, { status: 500 });
  }
}
