import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const { userId } = await req.json();
    
    // Validate request
    if (!userId) {
      return NextResponse.json({ error: 'Missing userId' }, { status: 400 });
    }

    // Since the AWS Bedrock Lambda isn't fully configured / wired in the `.env` yet,
    // we return a polished, heavily-formatted mock payload representing an AI response.
    // Replace this logic with the actual fetch(process.env.BEDROCK_LAMBDA_URL) when ready.

    // Await mock delay to simulate heavy LLM generation
    await new Promise(r => setTimeout(r, 2000));

    const mockAiPlan = `Based on your recent daily logs and clinical data, here is your synthesized daily plan:
    
### ☀️ Morning Routine
- **Hydration Kickstart**: Drink 1 large glass (16oz) of water immediately upon waking to counteract overnight dehydration.
- **Heart-Healthy Breakfast**: Swap processed cereals for oatmeal with chia seeds. This specifically targets lowering your LDL cholesterol currently in the risk band.
- **Medication Compliance**: Take your BP medication with food at 8:30 AM.

### 🏃‍♂️ Midday Activity
- **Movement Snack**: Break up sedentary blocks. Based on your recorded 7,500 steps, let's push for a 15-minute brisk walk after lunch to reach 9,000 steps today.
- **Stress Management**: You recorded a stress level of 8/10 yesterday. Dedicate 5 minutes to box-breathing at 2 PM.

### 🌙 Evening Wind-down
- **Smoking Cessation**: You successfully reduced your intake to 4 cigarettes yesterday! If a craving hits post-dinner, try chewing cinnamon gum.
- **Sleep Hygiene**: Disconnect from screens by 10 PM. You've averaged only 6 hours of sleep this week, which significantly impacts blood pressure recovery.

*Generated by Prosper Bedrock AI Engine.*`;

    return NextResponse.json({ success: true, plan: mockAiPlan });

  } catch (error: any) {
    console.error('API /health-plan/generate Error:', error);
    return NextResponse.json({ error: 'Failed to generate plan securely.' }, { status: 500 });
  }
}
